version: '3.4'

services:
  dev:
    image: node:12-alpine
    container_name: bq-api-node
    command:  sh -c "npm run dev && npm run migrate"
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:cached
    networks:
      - store-network
    depends_on:
      - db

  db:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      # - POSTGRES_HOST_AUTH_METHOD=tru
    container_name: bq-api-node_db
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - store-network

volumes:
  database:

networks:
  store-network:
    driver: bridge